plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.strongcat'
version = '0.0.1-SNAPSHOT'
description = 'ingestion-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.awaitility:awaitility:4.2.0'
    testImplementation platform('org.testcontainers:testcontainers-bom:1.19.7')
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:kafka'
    testImplementation 'org.opensearch:opensearch-testcontainers:4.1.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    implementation 'org.opensearch.client:opensearch-java:2.8.0'
    implementation 'org.opensearch.client:opensearch-rest-client:2.8.0'
    implementation 'org.springframework.boot:spring-boot-starter-json'

    implementation 'commons-io:commons-io:2.22.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
